"""
Clock model with power-law noise for WP2 simulation.

Each clock produces a sequence of fractional frequency residuals
y_k at discrete sample times k*dt:

    y_k = white_freq_k + flicker_freq_k + random_walk_k
          + drift * (k*dt) + signal((k*dt))

The white-frequency component is i.i.d. (Gaussian or, for outlier
clocks, Student-t with finite ν). The flicker component is
fractional Gaussian noise (Davies-Harte; H = 0.9, generated by
src/noise.py:generate_flicker) rescaled to a target standard
deviation. The random-walk component is a cumulative-sum process.
Drift is a constant rate of frequency change. Signal is an
arbitrary user-supplied function of time.

Each clock also reports a declared per-sample uncertainty sigma,
which is what the IC observable consumes. By default the declared
sigma equals the white-frequency level — the part of the noise
budget the operator can characterise from short-term measurements.
A degradation factor scales both the actual white-frequency noise
and the declared sigma together; an underestimation factor
modifies only the declared sigma (for testing the WP1 worst-case
sigma sensitivity at the network level).

Reference parameters: active hydrogen maser from Panfilo & Arias
(2019, Table 1), at sampling tau = 1 day:
    sigma_y(white frequency) ~ 1.5e-15
    flicker floor             ~ 7e-16

Signal generators provided: sinusoidal, linear drift, step,
fold bifurcation (S8). All return callables of shape (t,) -> (t,).
"""

from dataclasses import dataclass, field
from typing import Callable, Optional, Sequence, Tuple

import numpy as np

from noise import generate_flicker


# ---------------------------------------------------------------
# Reference parameter sets
# ---------------------------------------------------------------

HYDROGEN_MASER_SIGMA_WHITE = 1.5e-15   # sigma_y at tau=1 day, white frequency
HYDROGEN_MASER_SIGMA_FLICKER = 7.0e-16  # flicker floor at tau~10 day


@dataclass
class ClockParams:
    """Per-clock noise and signal specification.

    All sigma values are per-sample standard deviations of fractional
    frequency residuals at the simulation timestep. Defaults give a
    Gaussian white-frequency-noise-only clock at unit scale; supply
    sigma_flicker / sigma_rw / drift / signal to enrich the model.

    Parameters
    ----------
    sigma_white : float
        Std of the per-sample white-frequency noise contribution.
    sigma_flicker : float
        Target std of the flicker (1/f frequency) component.
        Realised by rescaling fractional Gaussian noise (H=0.9).
    sigma_rw : float
        Per-step std of the random-walk-frequency increment.
    drift : float
        Constant linear drift in fractional frequency per unit time.
    signal : callable or None
        signal(t_array) -> array of additive frequency contributions.
    sigma_declared_factor : float
        Multiplier applied to the white-sigma reported per sample.
        sigma_declared = sigma_white * sigma_declared_factor. Use
        0.8 to model -20% systematic underestimation (WP1 entry 002).
    degradation_factor : float
        Multiplier applied uniformly to sigma_white, sigma_flicker,
        sigma_rw, and the declared sigma. Models a degraded clock
        (e.g. 3x noise; mentioned in proposal sec. WP2).
    heavy_tail_nu : float or None
        If set, white frequency noise is drawn from Student-t with
        nu degrees of freedom (rescaled to keep variance = sigma_white^2),
        rather than Gaussian. Models a heavy-tailed outlier clock.
    """

    sigma_white: float = 1.0
    sigma_flicker: float = 0.0
    sigma_rw: float = 0.0
    drift: float = 0.0
    signal: Optional[Callable[[np.ndarray], np.ndarray]] = None
    sigma_declared_factor: float = 1.0
    degradation_factor: float = 1.0
    heavy_tail_nu: Optional[float] = None


def hydrogen_maser(degradation_factor: float = 1.0,
                   heavy_tail_nu: Optional[float] = None,
                   signal: Optional[Callable] = None,
                   drift: float = 0.0) -> ClockParams:
    """Convenience constructor for a hydrogen-maser-like clock.

    Returns a ClockParams pre-populated with sigma_white = 1.5e-15
    and sigma_flicker = 7e-16 (Panfilo & Arias 2019, sampling
    tau = 1 day). Apply degradation_factor=3 for a degraded clock.
    """
    return ClockParams(
        sigma_white=HYDROGEN_MASER_SIGMA_WHITE,
        sigma_flicker=HYDROGEN_MASER_SIGMA_FLICKER,
        degradation_factor=degradation_factor,
        heavy_tail_nu=heavy_tail_nu,
        signal=signal,
        drift=drift,
    )


# ---------------------------------------------------------------
# Signal generators
# ---------------------------------------------------------------

def signal_sinusoidal(amplitude: float, period: float,
                      phase: float = 0.0,
                      onset: float = 0.0) -> Callable:
    """sinusoid amplitude * sin(2*pi*(t - onset)/period + phase) for t >= onset."""
    def _sig(t):
        out = np.zeros_like(np.asarray(t, dtype=float))
        active = t >= onset
        out[active] = amplitude * np.sin(
            2 * np.pi * (t[active] - onset) / period + phase)
        return out
    return _sig


def signal_linear_drift(rate: float, onset: float = 0.0) -> Callable:
    """rate * (t - onset) for t >= onset."""
    def _sig(t):
        out = np.zeros_like(np.asarray(t, dtype=float))
        active = t >= onset
        out[active] = rate * (t[active] - onset)
        return out
    return _sig


def signal_step(magnitude: float, onset: float) -> Callable:
    """Heaviside step of given magnitude at onset."""
    def _sig(t):
        return np.where(np.asarray(t) >= onset, magnitude, 0.0)
    return _sig


def signal_fold_bifurcation(epsilon: float,
                            r0: float = -1.0,
                            x0: float = 0.0,
                            onset: float = 0.0) -> Callable:
    """Fold-bifurcation residual signal for scenario S8.

    Models a control parameter r drifting linearly at rate epsilon
    from r0, with overdamped dynamics dx/dt = r + x^2. As r passes
    through 0 the lower fixed point x* = -sqrt(-r) collides with the
    upper one and the system loses a stable equilibrium. The signal
    returned is x(t), the residual frequency departure caused by
    the drifting servo. Integrated forward by explicit Euler with
    step = (t[1] - t[0]); intended for slowly-varying r where this
    is adequate.

    Parameters
    ----------
    epsilon : float
        dr/dt rate of control-parameter drift (typically small).
    r0 : float
        Initial r at t = onset; should be < 0 so the system starts
        on the lower stable branch.
    x0 : float
        Initial residual.
    onset : float
        Time at which drift begins.
    """
    def _sig(t):
        t = np.asarray(t, dtype=float)
        out = np.zeros_like(t)
        if len(t) < 2:
            return out
        dt = t[1] - t[0]
        x = x0
        r = r0
        for k, tk in enumerate(t):
            if tk < onset:
                out[k] = 0.0
                continue
            r = r0 + epsilon * (tk - onset)
            x = x + dt * (r + x * x)
            out[k] = x
            # Guard against blow-up after fold collapse
            if not np.isfinite(x) or abs(x) > 1e6:
                out[k:] = np.nan
                break
        return out
    return _sig


# ---------------------------------------------------------------
# Single-clock simulator
# ---------------------------------------------------------------

def simulate_clock(params: ClockParams,
                   T: int,
                   dt: float = 1.0,
                   rng: Optional[np.random.Generator] = None
                   ) -> Tuple[np.ndarray, np.ndarray]:
    """Simulate one clock for T samples of duration dt.

    Returns
    -------
    y : array of shape (T,)
        Fractional frequency residual at each step.
    sigma_declared : array of shape (T,)
        Per-sample declared uncertainty (constant across t for now).
    """
    if rng is None:
        rng = np.random.default_rng()

    deg = params.degradation_factor
    sigma_white = params.sigma_white * deg
    sigma_flicker = params.sigma_flicker * deg
    sigma_rw = params.sigma_rw * deg

    # White frequency noise
    if params.heavy_tail_nu is not None:
        nu = params.heavy_tail_nu
        if nu <= 2:
            raise ValueError(
                f"heavy_tail_nu must be > 2 for finite variance, got {nu}")
        # Scale Student-t so variance equals sigma_white^2
        raw = rng.standard_t(nu, T)
        white = raw * sigma_white * np.sqrt((nu - 2) / nu)
    else:
        white = rng.normal(0.0, sigma_white, T) if sigma_white > 0 \
            else np.zeros(T)

    # Flicker frequency noise: rescale fGn(H=0.9) to target sigma
    if sigma_flicker > 0:
        fgn = generate_flicker(T, H=0.9, rng=rng)
        std_fgn = np.std(fgn)
        flicker = fgn / std_fgn * sigma_flicker if std_fgn > 0 else np.zeros(T)
    else:
        flicker = np.zeros(T)

    # Random-walk frequency
    if sigma_rw > 0:
        rw = np.cumsum(rng.normal(0.0, sigma_rw, T))
    else:
        rw = np.zeros(T)

    t = np.arange(T, dtype=float) * dt

    # Linear drift
    drift_term = params.drift * t

    # Signal
    sig_term = params.signal(t) if params.signal is not None else 0.0

    y = white + flicker + rw + drift_term + sig_term

    sigma_declared = np.full(T, sigma_white * params.sigma_declared_factor)

    return y, sigma_declared


def simulate_network_clocks(params_list: Sequence[ClockParams],
                            T: int,
                            dt: float = 1.0,
                            rng: Optional[np.random.Generator] = None
                            ) -> Tuple[np.ndarray, np.ndarray]:
    """Simulate N clocks for T steps. Returns Y, Sigmas of shape (T, N)."""
    if rng is None:
        rng = np.random.default_rng()
    n = len(params_list)
    Y = np.zeros((T, n))
    Sigmas = np.zeros((T, n))
    for i, p in enumerate(params_list):
        Y[:, i], Sigmas[:, i] = simulate_clock(p, T, dt, rng)
    return Y, Sigmas


# ---------------------------------------------------------------
# Scenario builders
# ---------------------------------------------------------------

def build_scenario_clocks(n: int,
                          n_signal: int = 0,
                          signal_factory: Optional[Callable[[int], Callable]] = None,
                          n_degraded: int = 1,
                          degradation_factor: float = 3.0,
                          heavy_tail_index: Optional[int] = None,
                          heavy_tail_nu: float = 3.0,
                          base: Optional[ClockParams] = None) -> list:
    """Construct a per-clock parameter list for a WP2 scenario.

    Parameters
    ----------
    n : int
        Total number of clocks.
    n_signal : int
        Number of clocks that receive an injected signal (the first
        n_signal clocks).
    signal_factory : callable(i) -> signal_func
        Returns the signal function for clock i (allows different
        phases/amplitudes per signal clock). If None, no signal is
        injected even when n_signal > 0.
    n_degraded : int
        Number of clocks at the end of the list with degradation_factor
        applied.
    degradation_factor : float
        Multiplier on noise for degraded clocks (default 3x per proposal).
    heavy_tail_index : int or None
        Index of one clock that should use Student-t white noise;
        defaults to no heavy-tail clock.
    heavy_tail_nu : float
        Student-t degrees of freedom for the heavy-tail clock.
    base : ClockParams or None
        Template parameters for nominal clocks. Defaults to a
        hydrogen-maser-like clock.

    Returns
    -------
    list of ClockParams of length n.
    """
    if base is None:
        base = hydrogen_maser()

    out = []
    for i in range(n):
        sig = signal_factory(i) if (signal_factory and i < n_signal) else None
        deg = degradation_factor if i >= n - n_degraded else 1.0
        nu = heavy_tail_nu if i == heavy_tail_index else None
        out.append(ClockParams(
            sigma_white=base.sigma_white,
            sigma_flicker=base.sigma_flicker,
            sigma_rw=base.sigma_rw,
            drift=base.drift,
            signal=sig,
            sigma_declared_factor=base.sigma_declared_factor,
            degradation_factor=deg,
            heavy_tail_nu=nu,
        ))
    return out
